# Generated by Django 3.2.5 on 2021-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locator',
            name='title',
        ),
    ]
